package com.example.kaplat.server.enums;

public enum ErrorMessageEnum {
    DIVISION_BY_0, FACTORIAL, NO_SUCH_OPERATION, NOT_ENOUGH_ARGUMENTS, TOO_MANY_ARGUMENTS, NOT_ENOUGH_ARGUMENTS_WITH_COUNTER, ERROR_OPERATION_INVOKED;
}
